image:
  repository: europe-west1-docker.pkg.dev/devops-sandbox-418714/docker-registry/metric-stream-service
  tag: latest
  pullPolicy: IfNotPresent
imagepullSecrets:
  - name: private-registry-secret
service:
  port: 8080